### ISSUE TITLE
Elytra equipped while swimming

### ISSUE THREAD

**Issue by Ivan0xFF** [Szum123321/elytra_swap#12]
I love this mod, thank you so much for your work!

I'm running into an issue with my Elytra will always be on when I'm underwater.

I'm on version 1.6.0 on Minecraft 1.15.2. Let me know if there's any log or anything I could provide.

Thanks!

**Comment by Szum123321** [comment]
That's interesting. I'll take a look at this soon.

**Comment by Szum123321** [comment]
Repaired in 1.6.1.

**Comment by Ivan0xFF** [comment]
Works perfectly! Thanks for the quick fix!
