### ISSUE TITLE
Take off

### ISSUE THREAD

**Issue by AC-ID** [Szum123321/elytra_swap#13]
I can't take off with firework from halve blocks like slabs, if I walk over one block to a full block it works fine.

**Comment by Szum123321** [comment]
Interesting. I'll take a look at this soon. 

Thanks for reporting the bug!

**Comment by Szum123321** [comment]
By the way, could you provide information such as mod and minecraft version?
Thanks!

**Comment by AC-ID** [comment]
Sure, latest stable Minecraft version (1.15.2) and latest version of your mod (elytra_swap-1.6.1-1.15.jar).

**Comment by Szum123321** [comment]
Repaired in commit 207b87f1978a5da515fb74c9011af532557fa8ed

Than you for your help and sorry that it took so long.

**Comment by AC-ID** [comment]
Mate 6 days, it didn't took long at all ...

I will test it and give you a final feedback.

**Comment by AC-ID** [comment]
Thanks, now it works even on slabs.

**Comment by Szum123321** [comment]
Happy to hear!

Once again thank you for reporting it!
