### ISSUE TITLE
[1.16.1] Chest plate won't swap back on landing

### ISSUE THREAD

**Issue by Ivan0xFF** [Szum123321/elytra_swap#15]
As the title says, the chest plate won't be re-equipped when landing. Everything else appears to work great on 1.16.1.

Thanks for the fast update!

**Comment by Szum123321** [comment]
Do you have Trinkets installed?

**Comment by Ivan0xFF** [comment]
No, my installed mods are the following:

appleskin-mc1.16-fabric-1.0.11.jar
elytra_swap-1.6.3-1.16.1.jar
lithium-fabric-mc1.16.1-0.5.0-rc1.jar
betterSignsAndFrames-0.6.0.jar
fabric-api-0.13.1+build.370-1.16.jar
phosphor-fabric-mc1.16.1-0.6.0+build.7.jar

**Comment by Szum123321** [comment]
Repaired in a8a676330862ee29ddc39797d6d93fcda6975575. New version should be available soon on both curseforge and here.
Thank you for reporting this bug!
