### ISSUE TITLE
Suggestion: toggle for the 'automatic swap'

### ISSUE THREAD

**Issue by MeeniMc** [Szum123321/elytra_swap#17]
I see you have a toggle config for the 'rocket autoswitch'. 

I'd like to have a similar toggle for the 'fall autoswitch'. 

I actually enjoy a lot the rocket behavior, but I prefer to have the vanilla mode for falls.

Thanks for a great addon!

**Comment by Szum123321** [comment]
If by 'rocket autoswitch' you mean 'useFireworks' config entry, then yes, i can add similar thing for disabling elytra switch in the next release.

**Comment by Szum123321** [comment]
Resolved in 2.2.0
