### ISSUE TITLE
Incompatibility With Netherite Plus

### ISSUE THREAD

**Issue by Tofugrass** [Szum123321/elytra_swap#18]
There is a small bug when interacting with the Netherite Plus mod. 

When the user is wearing Netherite Elytra, and does not have a normal elytra to swap to, the take off feature does not work. 

When the user is wearing Netherite Elytra, and DOES HAVE A NORMAL ELYTRA TO SWAP TO, the take off feature works fine, and the user can take off while wearing the netherite elytra. When the user descends, the netherite elytra are treated as a chestplate, so the user swaps to normal elytra, but replaces it with netherite elytra upon landing. 

I think netherite elytra are being treated as a chestplate rather than an elytra item.

**Comment by Tofugrass** [comment]
I believe the JSON is malformed in https://github.com/Szum123321/elytra_swap/blob/2.x/src/main/resources/elytra_like_item_set.json . 

The A on line 9 is causing errors. Commit 6678e9a.

**Comment by Szum123321** [comment]
Yes, that A shouldn't be there but I committed it yesterday and that A is not present in any of the releases.

**Comment by Szum123321** [comment]
Ok, so I tested that and everything seems to be ok. So now I have to ask you a few questions like, what additional mods are you using?

**Comment by Tofugrass** [comment]
Can you push the new build? It might just fix itself with the new build. We should try that before anything else.

**Comment by Szum123321** [comment]
Ok, I'll do that today, but, once again, it wasn't broken because of that A

**Comment by Tofugrass** [comment]
The only mods I have are fabric api and netherite plus

**Comment by Szum123321** [comment]
But what versions?

**Comment by Tofugrass** [comment]
ive tried a bunch of versions. which combination works?

**Comment by Szum123321** [comment]
Yesterday this configuration wokred for me:
- Minecraft 1.16.2
- fabric-api-0.19.0+build.398-1.16
- elytra_swap-2.1.0-1.16.1
- netherite-plus-mod-beta-1.9.1

**Comment by Tofugrass** [comment]
so you are able to use netherite elytra from a standing position with only firework rockets in your inventory?

**Comment by Szum123321** [comment]
yes

**Comment by Tofugrass** [comment]
what fabric loader build?

**Comment by Szum123321** [comment]
fabric-loader-0.9.2+build.206-1.16.2

**Comment by Szum123321** [comment]
Have you tried deleting config?

**Comment by Szum123321** [comment]
Wow, I think you're right. It just stopped working.

**Comment by Tofugrass** [comment]
imagine that

**Comment by Tofugrass** [comment]
push the fix lmao

**Comment by Tofugrass** [comment]
it might not fix it but then at least ill be on the same build as you and we can troubleshoot

**Comment by Szum123321** [comment]
Since the last release I changed quite a bit the mod compatibility part, so that's probably why it works now. I have to do some more testing, but if you would like I can share current test build with you

**Comment by Tofugrass** [comment]
Yes that would be great, I can help test.

**Comment by Szum123321** [comment]
Just give me a minute to build everything for 1.16.2

**Comment by Szum123321** [comment]
[elytra_swap-2.1.1-1.16.2.tar.gz](https://github.com/Szum123321/elytra_swap/files/5113686/elytra_swap-2.1.1-1.16.2.tar.gz)
Github doesn't allow jars so I had to tar it

**Comment by Tofugrass** [comment]
I am failing to start minecraft with this version. 
Here is a stracktrace 
at net.szum123321.elytra_swap.inventory.ElytraItemFilter.<init>(ElytraItemFilter.java:67)
	at net.szum123321.elytra_swap.ElytraSwap.lambda$onInitialize$0(ElytraSwap.java:64)
	at net.minecraft.class_310.handler$zdf000$atClientStart(class_310.java:4800)
	at net.minecraft.class_310.<init>(class_310.java:576)

**Comment by Tofugrass** [comment]
Additionally:

java.lang.NoSuchMethodError: java.util.stream.Collectors.toUnmodifiableSet()Ljava/util/stream/Collector;
	at net.szum123321.elytra_swap.inventory.ElytraItemFilter.<init>(ElytraItemFilter.java:67)
	at net.szum123321.elytra_swap.ElytraSwap.lambda$onInitialize$0(ElytraSwap.java:64)

**Comment by Szum123321** [comment]
Oh! Right, I'm guessing you're using java 8?

**Comment by Tofugrass** [comment]
oh, probably. is there a java 9 i should update to?

**Comment by Szum123321** [comment]
No, I just use  java 11 most of the time, so I might be possible that I've used feature that just doesn't exist in java 8.

**Comment by Szum123321** [comment]
[elytra_swap-2.1.1-1.16.2.tar.gz](https://github.com/Szum123321/elytra_swap/files/5113717/elytra_swap-2.1.1-1.16.2.tar.gz)
It should all work now

**Comment by Tofugrass** [comment]
Works in Java 11. I did not try it in 8. 
Thank you very much good sir.

**Comment by Szum123321** [comment]
Ok, thanks for help with testing! New release should be available soon!
