### ISSUE TITLE
elytra_swap-2.2.0-1.16.2.jar crashes on 1.16.1

### ISSUE THREAD

**Issue by calloatti** [Szum123321/elytra_swap#19]
https://www.curseforge.com/minecraft/mc-mods/elytra-swap/files/3039912

https://paste.ee/p/vwceT

Maybe untag it as 1.16.1

**Comment by Szum123321** [comment]
I'm sorry, but it looks like the crash was caused by one of the wrenchanything libraries.

You should report it to its developers, not me.
