### ISSUE TITLE
the whole mod is unintuitive and poorly designed

### ISSUE THREAD

**Issue by Tofugrass** [Szum123321/elytra_swap#22]
what direction the player is facing is ignored entirely, and the player always takes off at a weird slightly upwards angle.

it is impossible to take off in any other angle.

if you are looking down from high up and take off, you go even higher. 

doesnt fit with vanilla flight mechanics. since vanilla flight goes what direction the player is facing. this mod does not even take that into consideration.

a very weird approach to a simple problem.

hopefully this one gets fixed or a better one gets released for fabric. 

this mod for forge does the same thing but in a way that is untuitive, fits with vanilla flight mechanics, and is actually really well done: https://www.curseforge.com/minecraft/mc-mods/easy-elytra-takeoff

**Comment by Tofugrass** [comment]
You do realize that you can't takeoff with a firework if you are looking at a block? In order to take off downwards, there would have to be open space downwards. As in, the player is above something and actually wants to travel downwards. If the player ACTUALLY wants to travel downwards, why are you sending him up?

**Comment by Szum123321** [comment]
You know, I'm reading your messages, you don't have to post them everywhere

**Comment by Szum123321** [comment]
And I'm just thinking what to say
