### ISSUE TITLE
Can't take off from water

### ISSUE THREAD

**Issue by MeeniMc** [Szum123321/elytra_swap#29]
### Problem:

Impossible to take-off from water/surface swimming. 

### Vanilla behavior:

One can take-off from water by double jumping with elytra equipped, and then using a rocket.

### Mod behavior:

1. Impossible to equip elytra in water: armor will be reinstalled instantly
2. double jump without elytra in water doesn't let the player hover long enough to auto-equip elytra.
3. rocket launch in water does not work, even when targeting some air blocks above water. 

### Desired behavior: 

Use a rocket while 'surface swimming' launches the player in the air, equip elytra.

**Comment by Szum123321** [comment]
Thank you for your report.

What version are you using? I'm quite sure I repaired it at some point, possibly in dev branch.

**Comment by MeeniMc** [comment]
2.2.0-1.16.1 (on MC 1.16.3)
