### ISSUE TITLE
Chestplate Wont Swap out 

### ISSUE THREAD

**Issue by ShinoAsada** [Szum123321/elytra_swap#8]
I tried jumping off a 90 block ledge in a survival world and my chest plate did not swap out with my elytra in my inventory. nor does the mod tell me if I have it enabled or disabled.  this took place in the overworld.

**Comment by ShinoAsada** [comment]
(newest 1.15 version)

**Comment by Szum123321** [comment]
Could you provide more info like what exactly fabric version are you using and what additional mods do you have installed?

**Comment by Szum123321** [comment]
Also did it happen on singleplayer or on some server?

**Comment by Szum123321** [comment]
Are you still there?

**Comment by ShinoAsada** [comment]
This is on a Server and i had Fabric-loader-0.7.8+build.189-1.15.2 
![Capture](https://user-images.githubusercontent.com/49826555/79057988-81648b00-7c1c-11ea-9c25-221124d63294.PNG)

**Comment by ShinoAsada** [comment]
I also tried it in a single-player server and it didn't work either

**Comment by Szum123321** [comment]
Are you sure you have elytra Swap installed? Because I do not see it in your mod list. Also do you have file called elytra_swap.json5 in your co figs?

**Comment by ShinoAsada** [comment]
I did have it at the time but then, later on, I removed it since it wasn't working

**Comment by Szum123321** [comment]
I cannot reproduce the problem. Here is jar with few changes that might make it work. Please test it and tell me if something changed and if you could please answer the rest of my questions.
[elytra_swap_1.4.3B.zip](https://github.com/Szum123321/elytra_swap/files/4469195/elytra_swap_1.4.3B.zip)

**Comment by Szum123321** [comment]
So?

**Comment by Szum123321** [comment]
Closing because of months of inactivity
