### ISSUE TITLE
Please make it work on servers

### ISSUE THREAD

**Issue by Dexapnow** [Szum123321/elytra_swap#9]
Yeah, just that, if it does work on server and I'm just missing something, sorry.
I have tried it in singleplayer and on server with this mod installed and it works fine.

**Comment by Szum123321** [comment]
It should work on server on this own without being installed on client, but then you need to set noModPlayersHandlingMethod in config file to one. Than make sure you have enabled it. You can do this by typing /swap true to enable. If it still does not work please provide more info such as additional what mods you have installed.

**Comment by Dexapnow** [comment]
Mi chodziło o to że miałem to na cliencie a nie na serwerze i chciałem to użyć jako troche taką przewage ale nie działa ;-; (na serverze nie ma, na cliencie jest)

**Comment by Szum123321** [comment]
To w ten sposób nigdy nie zadziała. Mod musi być zainstalowany na serverze aby działać. Co prawda automatyczne przekładanie zbroi i elytry można teoretycznie zrobić tylko na kliencie ale raczej tego nie będę implementować.
